INSERT INTO public.detail (description,"jobId") VALUES
	 ('Our computational challenges are so big, complex and unique we can''t just purchase off-the-shelf hardware, we''ve got to make it ourselves. Your team designs and builds the hardware, software and networking technologies that power all of Google''s services. As a Hardware Engineer, you design and build the systems that are the heart of the world''s largest and most powerful computing infrastructure. You develop from the lowest levels of circuit design to large system design and see those systems all the way through to high volume manufacturing. Your work has the potential to shape the machinery that goes into our cutting-edge data centers affecting millions of Google users.',1),
	 ('As a Supplier Development Engineering Manager, you will be responsible for leading a highly technical team of Subject Matter Experts in mechanical materials, tools, and processes. This team works closely with Architecture, Materials Engineering, Early Involvement Engineers, and suppliers to develop exceptional, innovative, and sustainable designs assessing manufacturing technologies and process development feasibility and scalability. You will develop leading edge manufacturing processes, establish process capability, and manage quality and inspection systems to consistently deliver products into Mass Production. You''ll drive technical and operational leadership with a cross-functional organization for material, process, fixtures, and equipment.',1),
	 ('Google''s mission is to organize the world''s information and make it universally accessible and useful. Our Devices & Services team combines the best of Google AI, Software, and Hardware to create radically helpful experiences for users. We research, design, and develop new technologies and hardware to make our user''s interaction with computing faster, seamless, and more powerful. Whether finding new ways to capture and sense the world around us, advancing form factors, or improving interaction methods, the Devices & Services team is making people''s lives better through technology.',1),
	 ('The US base salary range for this full-time position is $159,000-$239,000 + bonus + equity + benefits. Our salary ranges are determined by role, level, and location. The range displayed on each job posting reflects the minimum and maximum target salaries for the position across all US locations. Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training. Your recruiter can share more about the specific salary range for your preferred location during the hiring process.',1),
	 ('Please note that the compensation details listed in US role postings reflect the base salary only, and do not include bonus, equity, or benefits. Learn more about benefits at Google.',1),
	 ('Our computational challenges are so big, complex and unique we can''t just purchase off-the-shelf hardware, we''ve got to make it ourselves. Your team designs and builds the hardware, software and networking technologies that power all of Google''s services. As a Hardware Engineer, you design and build the systems that are the heart of the world''s largest and most powerful computing infrastructure. You develop from the lowest levels of circuit design to large system design and see those systems all the way through to high volume manufacturing. Your work has the potential to shape the machinery that goes into our cutting-edge data centers affecting millions of Google users.',5),
	 ('Google''s mission is to organize the world''s information and make it universally accessible and useful. Our Devices & Services team combines the best of Google AI, Software, and Hardware to create radically helpful experiences for users. We research, design, and develop new technologies and hardware to make our user''s interaction with computing faster, seamless, and more powerful. Whether finding new ways to capture and sense the world around us, advancing form factors, or improving interaction methods, the Devices & Services team is making people''s lives better through technology.',5),
	 ('The US base salary range for this full-time position is $102,000-$150,000 + bonus + equity + benefits. Our salary ranges are determined by role, level, and location. The range displayed on each job posting reflects the minimum and maximum target salaries for the position across all US locations. Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training. Your recruiter can share more about the specific salary range for your preferred location during the hiring process.',5),
	 ('Please note that the compensation details listed in US role postings reflect the base salary only, and do not include bonus, equity, or benefits. Learn more about benefits at Google.',5),
	 ('Systems Development Engineering (SDE) at Google is a role where you manage services and systems at scale. SDEs creatively put their engineering discipline to use automating the mundane and reducing toil. We don’t just write code to fix bugs, but emphasize the development of tools and solutions that fix classes of problems. We know it’s hard to control what you can’t measure – so we focus on observability: instrumenting first, then turning data into knowledge, and finally knowledge into action. We know that the operational efficiency of Google systems, services, virtual compute environments and the operating systems that power them impact the environment, not just the bottom line. We know that working together we can do more, and that community matters.
',6);
INSERT INTO public.detail (description,"jobId") VALUES
	 ('Google brings together people with a wide variety of backgrounds, experiences and perspectives. We encourage them to collaborate, think big and take risks in a blame-free environment. We promote self-direction to work on meaningful projects, while we also strive to create an environment that provides the support and mentorship needed to learn and grow.',6),
	 ('Together we engineer and build the infrastructure, tools, access and telemetry for systems that enable orchestration of Google-scale services. Come build things that matter.',6),
	 ('Bare Metal Solution provides a Google Cloud Platform (GCP) service that allows customers to run their enterprise workloads on traditional servers in colocation spaces adjacent to GCP, providing the capability to the enterprise customers to exit their data centers and migrate to the Google Cloud with all the workloads. The team builds the service that is integrated with GCP allowing customers to have consistent experiences with servers.',6),
	 ('Google Cloud accelerates every organization’s ability to digitally transform its business and industry. We deliver enterprise-grade solutions that leverage Google’s cutting-edge technology, and tools that help developers build more sustainably. Customers in more than 200 countries and territories turn to Google Cloud as their trusted partner to enable growth and solve their most critical business problems.',6),
	 ('At Google, we follow a simple but vital premise: "Focus on the user and all else will follow." User Experience Researchers (UXRs) make this possible.',10),
	 ('Google User Experience (UX) is made up of multi-disciplinary teams of UX Designers, Researchers, Writers, Content Strategists, Program Managers, and Engineers: we care deeply about the people who use our products. The UX team plays an integral part in gathering insights about the needs, attitudes, emotions, and behaviors of people who use our products to inspire and inform design. We collaborate closely with each other and with engineering and product management to create industry-leading products that deliver value for the people who use them, and for Google’s businesses.
',10),
	 ('As a User Experience Researcher (UXR), you’ll help your team of UXers, product managers, and engineers understand user needs. You’ll work with stakeholders across functions and levels and have impact at all stages of product development. You’ll play a critical role in creating useful, usable, and delightful products. You’ll explore user behaviors and motivations by conducting primary research such as field studies, interviews, diary studies, participatory workshops, ethnography, surveys, usability testing, and logs analysis.',10),
	 ('The UXR community at Google is unique and will help you do your best work. You’ll have the opportunity to work with and learn from UXRs across Google through regular meetups, mentor programs, and access to internal research tools.',10),
	 ('The Creator Support team designs and builds products to support creators at scale through authoritative data, internal tools, creator facing products, and advanced technologies like Generative-AI virtual help assistants. The team strives to make interactions easy, helpful, and empowering.',10),
	 ('At YouTube, we believe that everyone deserves to have a voice, and that the world is a better place when we listen, share, and build community through our stories. We work together to give everyone the power to share their story, explore what they love, and connect with one another in the process. Working at the intersection of cutting-edge technology and boundless creativity, we move at the speed of culture with a shared goal to show people the world. We explore new ideas, solve real problems, and have fun — and we do it all together.',10);
INSERT INTO public.detail (description,"jobId") VALUES
	 ('At Google, we follow a simple but vital premise: "Focus on the user and all else will follow." Google’s UX leaders help define and drive the future of Google design. They create and clarify product strategy, conceptualize UX ecosystems in ways that mitigate complexity, and inspire teams to push the boundaries of what’s possible. They possess a clear vision of the future of user experience and have the courage to pursue forward-thinking design.',9),
	 ('Google User Experience (UX) is made up of multi-disciplinary teams of UX Designers, Researchers, Writers, Content Strategists, Program Managers, and Engineers: we care deeply about the people who use our products. You are a thoughtful team leader, manager, systems-level design thinker, and visionary - with strong instincts and outstanding intuition informed by user needs and insights. You''ll be responsible for guiding the careers of your team members, working closely with each of them to help them realize their full potential.',9),
	 ('UX Design Managers are fierce advocates for the people who use our products as well as the members of their teams. They have a practiced eye for effective design, and are committed to creating elegantly simple user experiences from otherwise complex workflows.',9),
	 ('In this role, you’ll take the time to understand not just the execution side of UX, but also the business aspects of the products we build. You’ll collaborate with leaders of other UX, Engineering, and Product Management teams to create innovative experiences across all of Google’s products, leveraging your passion for brand, craft, and design quality.',9),
	 ('At YouTube, we believe that everyone deserves to have a voice, and that the world is a better place when we listen, share, and build community through our stories. We work together to give everyone the power to share their story, explore what they love, and connect with one another in the process. Working at the intersection of cutting-edge technology and boundless creativity, we move at the speed of culture with a shared goal to show people the world. We explore new ideas, solve real problems, and have fun — and we do it all together.',9),
	 ('As the Director of UX, you will lead a global team of UX designers and writers to create the next-generation of payment experiences for first-party Google products. You''ll drive collaboration, transparency, and clarity between multiple product areas and functions, while fostering a culture of user-centric design. You will create simple, elegant, and reusable payment patterns that scale across numerous design languages, products, and surfaces.',8),
	 ('Whether it is paying online with Autofill, using tap and pay in stores, or using the Google Pay app, the Payments team at Google is focused on making payments simple, seamless, and secure. In addition to consumer payment technologies, the Payments team also powers the money movement between Google and its consumers and businesses.',8),
	 ('The US base salary range for this full-time position is $253,000-$363,000 + bonus + equity + benefits. Our salary ranges are determined by role, level, and location. The range displayed on each job posting reflects the minimum and maximum target salaries for the position across all US locations. Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training. Your recruiter can share more about the specific salary range for your preferred location during the hiring process.',8),
	 ('Please note that the compensation details listed in US role postings reflect the base salary only, and do not include bonus, equity, or benefits. Learn more about benefits at Google.',8),
	 ('At Google, we follow a simple but vital premise: "Focus on the user and all else will follow." Google’s Motion Designers collaborate with cross-functional partners to create desirable and relevant product experiences that consistently elevate the Google brand. They help people make sense of their world by choreographing experiences that feel fluid, natural, and informative.',7);
INSERT INTO public.detail (description,"jobId") VALUES
	 ('Google User Experience (UX) is made up of multi-disciplinary teams of UX Designers, Researchers, Writers, Content Strategists, Program Managers, and Engineers: we care deeply about the people who use our products. The UX team plays an integral part in gathering insights about the attitudes, emotions, and behaviors of people who use our products to inspire and inform design. We collaborate closely with each other and with engineering and product management to create industry-leading products that deliver value for the people who use them, and for Google’s businesses.',7),
	 ('As a Motion Designer, you’ll apply your passion for animation to simplify complex interactions and solve challenging design problems. You’ll help define and implement Google’s motion design language and you’ll think critically about how motion reinforces Google’s UX brand, enhances interactivity, and delights our users.',7),
	 ('Google Photos is a photo sharing and storage service developed by Google. Photos is one of the most sought after products at Google and is looking for both client-side (web and mobile), with server-side (search, storage, serving) and machine intelligence (learning, computer vision) Software Engineers. We are dedicated to making Google experiences centered around the user.',7),
	 ('The US base salary range for this full-time position is $142,000-$211,000 + bonus + equity + benefits. Our salary ranges are determined by role, level, and location. The range displayed on each job posting reflects the minimum and maximum target salaries for the position across all US locations. Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training. Your recruiter can share more about the specific salary range for your preferred location during the hiring process.',7),
	 ('Please note that the compensation details listed in US role postings reflect the base salary only, and do not include bonus, equity, or benefits. Learn more about benefits at Google.',7);
